name: sheet
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  gsheets: ^0.5.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  rxdart: ^0.27.7
  go_router: ^13.2.4
  logger: ^2.2.0
  shared_preferences: ^2.2.3
  timezone: ^0.9.2
  intl: ^0.19.0
  path_provider: ^2.1.3
  connectivity_plus: ^6.0.2
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/a.json
    - assets/images/

  fonts:
    - family: firacode
      fonts:
        - asset: assets/fonts/FiraCode-Retina.ttf
    - family: jetbrainsmono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Regular.ttf
    - family: rubikmono
      fonts:
        - asset: assets/fonts/RubikMonoOne-Regular.ttf